# Autogenerated wrapper script for IAIMbedTLS_jll for aarch64-apple-darwin
export libiaimbedcrypto, libiaimbedtls, libiaimbedx509

JLLWrappers.@generate_wrapper_header("IAIMbedTLS")
JLLWrappers.@declare_library_product(libiaimbedcrypto, "@rpath/libiaimbedcrypto.5.dylib")
JLLWrappers.@declare_library_product(libiaimbedtls, "@rpath/libiaimbedtls.13.dylib")
JLLWrappers.@declare_library_product(libiaimbedx509, "@rpath/libiaimbedx509.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libiaimbedcrypto,
        "lib/libiaimbedcrypto.2.24.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libiaimbedtls,
        "lib/libiaimbedtls.13.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libiaimbedx509,
        "lib/libiaimbedx509.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
