# Autogenerated wrapper script for IAIMbedTLS_jll for x86_64-w64-mingw32
export libiaimbedcrypto, libiaimbedtls, libiaimbedx509

JLLWrappers.@generate_wrapper_header("IAIMbedTLS")
JLLWrappers.@declare_library_product(libiaimbedcrypto, "libiaimbedcrypto.dll")
JLLWrappers.@declare_library_product(libiaimbedtls, "libiaimbedtls.dll")
JLLWrappers.@declare_library_product(libiaimbedx509, "libiaimbedx509.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libiaimbedcrypto,
        "bin\\libiaimbedcrypto.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libiaimbedtls,
        "bin\\libiaimbedtls.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libiaimbedx509,
        "bin\\libiaimbedx509.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
